trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'job one'
  steps:
  - script: echo Hello, world 1!
    displayName: 'Run a one-line script 1'

- job: 'job two'
  steps:
  - script: echo Hello, world 2!
    displayName: 'Run a one-line script 2'
